---
volumes:
  pg-data:
  spacy-data:

services:
  jupyter:
    build:
      dockerfile: docker/jupyter/Dockerfile
      context: ./
    ports:
      - 8888:8888
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    volumes:
      - $HOME/Projects/Notebooks/:/home/jovyan/work
      - $HOME/Data/:/home/jovyan/data
      - $HOME/.aws/:/home/jovyan/.aws

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pg-data:/var/lib/postgresql/data
